# Generated by Django 5.0.4 on 2024-04-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0004_alter_timetablerollouts_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='created_by_user',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='modified_by_user',
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_definition_creator', to='FacultyAttendanceSystem.faculty'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_definition_modifier', to='FacultyAttendanceSystem.faculty'),
        ),
        migrations.AlterField(
            model_name='timetablerollouts',
            name='class_attedance',
            field=models.BooleanField(default=False, verbose_name='Faculty Attendance'),
        ),
        migrations.AlterField(
            model_name='timetablerollouts',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_modified_by', to='FacultyAttendanceSystem.faculty'),
        ),
    ]
