# Generated by Django 5.0.4 on 2024-04-10 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0005_remove_timetable_created_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_definition_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='modified_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_definition_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetablerollouts',
            name='class_attedance',
            field=models.BooleanField(default=False, verbose_name='Faculty Attedance'),
        ),
        migrations.AlterField(
            model_name='timetablerollouts',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
