# Generated by Django 5.0.4 on 2024-07-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midexamscheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Mid Exam Date')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mid Exam Title')),
                ('Semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_midexams', to='FacultyAttendanceSystem.semester')),
            ],
        ),
    ]
