# Generated by Django 5.0.4 on 2024-07-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0002_midexamscheduler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midexamscheduler',
            old_name='Semester',
            new_name='semester',
        ),
    ]
