# Generated by Django 5.0.4 on 2024-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0002_alter_studentclass_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesession',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='enrollment_no',
            field=models.CharField(max_length=100),
        ),
    ]
