# Generated by Django 5.0.4 on 2024-04-10 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0002_classduration_room_semester_faculty_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='first_class_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='First Class of the semester'),
            preserve_default=False,
        ),
    ]
