# Generated by Django 5.0.4 on 2024-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0003_activesession_device_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
