# Generated by Django 5.0.4 on 2024-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0004_alter_activesession_device_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='enrollment_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
