# Generated by Django 5.0.4 on 2024-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0005_alter_activesession_device_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='activesession',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
