# Generated by Django 5.0.4 on 2024-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0006_remove_activesession_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='activesession',
            unique_together={('device_identifier', 'enrollment_no')},
        ),
    ]
