# Generated by Django 5.0.4 on 2024-04-10 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0006_remove_timetable_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablerollouts',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
