# Generated by Django 5.0.4 on 2024-07-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0007_alter_activesession_device_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20, unique=True, verbose_name='Enrollment Number')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='Banned At')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Duration (Hours)')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyAttendanceSystem.admincredentials', verbose_name='Faculty')),
            ],
        ),
    ]
