# Generated by Django 5.0.4 on 2024-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0007_alter_timetablerollouts_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Class End Time'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Class Start Time'),
        ),
    ]
