# Generated by Django 5.0.4 on 2024-07-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0008_bannedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedstudent',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyAttendanceSystem.faculty', verbose_name='Faculty'),
        ),
    ]
