# Generated by Django 5.0.4 on 2024-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0009_alter_bannedstudent_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.DeleteModel(
            name='BannedStudent',
        ),
    ]
