# Generated by Django 5.0.4 on 2024-04-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0009_alter_timetablerollouts_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
    ]
