# Generated by Django 5.0.4 on 2024-05-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0010_remove_faculty_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='workshift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_in', models.TimeField(blank=True, null=True)),
                ('punch_out', models.TimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.faculty')),
            ],
        ),
    ]
