# Generated by Django 5.0.4 on 2024-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0010_students_is_active_delete_bannedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Enrollment Number'),
        ),
    ]
