# Generated by Django 5.0.4 on 2024-05-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0011_workshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Class Start Time'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.faculty', verbose_name='faculty_id'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='punch_in',
            field=models.TimeField(blank=True, null=True, verbose_name='punch in'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='punch_out',
            field=models.TimeField(blank=True, null=True, verbose_name='punch out'),
        ),
    ]
