# Generated by Django 5.0.4 on 2024-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0012_alter_students_enrollment_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
        migrations.AddField(
            model_name='students',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Enrollment Number'),
        ),
        migrations.AlterUniqueTogether(
            name='students',
            unique_together={('device_identifier', 'enrollment_no')},
        ),
    ]
