# Generated by Django 5.0.4 on 2024-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0012_alter_workshift_date_alter_workshift_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Holiday event')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='EventScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Event Date')),
                ('start_time', models.TimeField(verbose_name='start event')),
                ('end_time', models.TimeField(verbose_name='end event')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Title')),
                ('Description', models.CharField(blank=True, max_length=400, null=True, verbose_name='Event Description')),
                ('faculty', models.ManyToManyField(blank=True, to='FacultyAttendanceSystem.faculty', verbose_name='Faculty')),
            ],
        ),
    ]
