# Generated by Django 5.0.4 on 2024-07-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
