# Generated by Django 5.0.4 on 2024-05-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0015_remove_subject_term_date_semester_term_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_type',
            field=models.CharField(blank=True, choices=[('lecture', 'lecture'), ('lab', 'lab'), ('lab-A1', 'lab-A1'), ('lab-A2', 'lab-A2'), ('lab-A3', 'lab-A3'), ('lab-B1', 'lab-B1'), ('lab-B2', 'lab-B2'), ('lab-B3', 'lab-B3'), ('lab-C1', 'lab-C1'), ('lab-C2', 'lab-C2'), ('lab-C3', 'lab-C3')], default='scheduled', max_length=200, null=True, verbose_name='Class Type'),
        ),
    ]
