# Generated by Django 5.0.4 on 2024-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0015_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='device_identifier',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
