# Generated by Django 5.0.4 on 2024-06-25 07:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0016_alter_timetable_class_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Students_class_name', models.CharField(max_length=200, null=True, verbose_name='Class Name')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_classes', to='FacultyAttendanceSystem.semester')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='Student_Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyAttendanceSystem.studentclass'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20, unique=True, verbose_name='Enrollment Number')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('Student_Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyAttendanceSystem.studentclass')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsRollouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_status', models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('break', 'break'), ('discontinued', 'discontinued')], default='scheduled', max_length=200, null=True, verbose_name='Class status')),
                ('student_attendance', models.BooleanField(default=False, verbose_name='Student Attendance')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('class_date', models.DateField(blank=True, null=True, verbose_name='Class date')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_rollout', to='FacultyAttendanceSystem.timetable', verbose_name='Class definition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_created_by', to=settings.AUTH_USER_MODEL)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_rollout', to='FacultyAttendanceSystem.classduration')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_faculty', to='FacultyAttendanceSystem.faculty')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_class_modified_by', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.room')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.students', verbose_name='Student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.subject', verbose_name='Subject')),
            ],
        ),
    ]
