# Generated by Django 5.0.4 on 2024-07-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0016_alter_students_device_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentsrollouts',
            name='timetable_rollout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_rollouts', to='FacultyAttendanceSystem.timetablerollouts', verbose_name='Timetable Rollout'),
        ),
        migrations.AlterField(
            model_name='timetablerollouts',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_rollout', to='FacultyAttendanceSystem.timetable', verbose_name='Class definition'),
        ),
        migrations.RemoveField(
            model_name='students',
            name='device_identifier',
        ),
    ]
