# Generated by Django 5.0.4 on 2024-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0017_studentclass_timetable_student_class_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='class_type',
            field=models.CharField(blank=True, choices=[('lecture', 'lecture'), ('lab', 'lab'), ('lab-A1', 'lab-A1'), ('lab-A2', 'lab-A2'), ('lab-A3', 'lab-A3'), ('lab-A4', 'lab-A4'), ('lab-B1', 'lab-B1'), ('lab-B2', 'lab-B2'), ('lab-B3', 'lab-B3'), ('lab-B4', 'lab-B4'), ('lab-C1', 'lab-C1'), ('lab-C2', 'lab-C2'), ('lab-C3', 'lab-C3'), ('lab-C4', 'lab-C4')], default='scheduled', max_length=200, null=True, verbose_name='Class Type'),
        ),
    ]
