# Generated by Django 5.0.4 on 2024-07-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0017_alter_students_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventScheduler',
        ),
    ]
