# Generated by Django 5.0.4 on 2024-06-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0018_alter_timetable_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Student_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Student Password'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Student_Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.studentclass'),
        ),
    ]
