# Generated by Django 5.0.4 on 2024-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0019_students_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
