# Generated by Django 5.0.4 on 2024-06-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyAttendanceSystem', '0020_activesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Student_Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyAttendanceSystem.studentclass', verbose_name='Student Class'),
        ),
    ]
